import type { Metadata } from "next";
import "./globals.css"
import { Poppins as FontSans } from "next/font/google"
import { Volkhov as FontSerif } from "next/font/google"
import Header from "@/components/Header";
import { cn } from "@/lib/utils"
import { Sheet } from '@/components/ui/sheet' 
import Footer from "@/components/Footer";

 
const fontSans = FontSans({
  subsets: ["latin"],
  display: 'swap',
  variable : "--font-poppins",
  weight : ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const fontSerif = FontSerif({
  subsets: ["latin"],
  display: 'swap',
  variable : "--font-Volkhov",
  weight : ["400","700"],
})

export const metadata: Metadata = {
  title: "Fasco - Buy the Quality",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  
          className={cn(
          `min-h-screen text-main`,
          fontSans.variable,
          fontSerif.variable
        )}
        >
          <Sheet />
          <Header />
          {children}
          <Footer />
      </body>
    </html>
  );
}
